version: "3.7"
services:
  application:
    container_name: spring-today-earth-app
    build: .
    ports:
      - "8080:8080"
    environment:
      TZ: "Asia/Seoul"
    volumes:
      - /Users/seungmin/study/earth-resources:/Users/seungmin/study/earth-resources
    restart: always